// <auto-generated />
using System;
using DragChain.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DragChain.API.Data.Migrations
{
    [DbContext(typeof(DragChainDbContext))]
    [Migration("20260429012534_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DragChain.API.Models.MeCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InnerArea")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("InnerHeight")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("InnerWidth")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Lp1")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Lp2")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Lp3")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("MaxWeight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("R1")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("R1Suffix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("R2")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("R2Suffix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("R3")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("R3Suffix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SpanBase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SpanSlope")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("BaseModel");

                    b.ToTable("MeCatalog");
                });

            modelBuilder.Entity("DragChain.API.Models.PipeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BendMultiplier")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Diameter")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Type");

                    b.ToTable("PipeTypes");
                });

            modelBuilder.Entity("DragChain.API.Models.WzlCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppPipes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BendLength")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Function")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InnerArea")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("InnerHeight")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("InnerWidth")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("InterferenceH2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinRadius")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MountingH1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OuterHeight")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("OuterWidth")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("RecRadius")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("ReservedK")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Stroke")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Function");

                    b.HasIndex("Model");

                    b.ToTable("WzlCatalog");
                });
#pragma warning restore 612, 618
        }
    }
}
